name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: calcdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        volumes:
          - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            --network=host \
            -v $(pwd)/db/migrations:/flyway/sql \
            flyway/flyway:latest \
            -url=jdbc:mariadb://127.0.0.1:3306/calcdb \
            -user=user -password=password migrate
