name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Install required tools
        run: | 
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet tool install --global dotnet-stryker

      - name: Run unit tests
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Generate report
        run: reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:coverage-report -reporttypes:Html

      - name: Run Mutation Tests
        run: dotnet stryker --threshold-high 80

      - name: Collect Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage-report

      - name: Collect Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mutation-test-report
          path: StrykerOutput
          
          
  deploy:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Deploy til Staging Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/calculator
            git pull origin main
            dotnet build
            sudo systemctl restart calculator
          EOF

  load_test: #k6
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Installer K6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Kør K6 Load Test
        run: k6 run tests/k6-test.js
  
  
  e2e_test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Installer TestCafé
        run: npm install -g testcafe

      - name: Kør E2E test
        run: testcafe chrome tests/e2e-test.js
      