name: workflow.yml

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Database Migration
  migrate-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Flyway migrations on Staging DB
        env:
          DB_HOST: ${{ vars.STAGING_DB_HOST }}
          DB_PORT: ${{ vars.STAGING_DB_PORT }}
          DB_NAME: ${{ vars.STAGING_DB_NAME }}
          DB_USER: ${{ vars.STAGING_DB_USER }}
          DB_PASSWORD: ${{ vars.STAGING_DB_PASSWORD }}
        run: |
          docker run --rm \
            -v $(pwd)/db/migrations:/flyway/sql \
            flyway/flyway:latest \
            -url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME} \
            -user=${DB_USER} -password=${DB_PASSWORD} \
            -baselineOnMigrate=true \
            migrate

  
  build:
    needs: migrate-database  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/calculator:$GITHUB_SHA

  # Step 3: Deploy to server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker container to server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            docker pull jakoc/calculator:$GITHUB_SHA
            docker stop calculator || true
            docker rm calculator || true
            docker run -d \
              --name calculator \
              -p 80:80 \
              -e DATABASE_CONNECTION_STRING="${{ vars.DATABASE_CONNECTION_STRING }}" \
              jakoc/calculator:$GITHUB_SHA
            echo "✅ Deployment completed successfully!"
          EOF

  # Step 4: Load Testing with K6
  load_test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install K6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Run K6 Load Test
        run: k6 run Tests/tests/k6-test.js

  # Step 5: E2E Testing with TestCafé
  e2e_test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install necessary dependencies
        run: |
          sudo apt update
          sudo apt install -y firefox
          sudo apt install -y libx11-xcb1 libdbus-glib-1-2

      - name: Install TestCafé
        run: npm install -g testcafe

      - name: Run E2E test with Firefox in headless mode
        run: testcafe firefox:headless Tests/tests/e2e-test.js --browser-init-timeout 50000
